[package]
name = "clap-completion-flag"
version = "1.1.0"
edition = "2024"
description = "A small utility to generate shell completion scripts for clap-based applications."
readme = "README.md"
homepage = "https://github.com/Paul-16098/clap-completion-flag"
repository = "https://github.com/Paul-16098/clap-completion-flag"
license-file = "LICENSE.txt"
keywords = ["clap", "completion"]
categories = ["command-line-interface"]

[dependencies]
carapace_spec_clap = "1.2.3"
clap = { version = "4.6.6", features = ["derive"] }
clap_complete = "4.6.9"
clap_complete_nushell = "4.6.2"

[dev-dependencies]
insta = "1.48.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
